#!/usr/bin/env bash
set -euo pipefail

# Build the complete offline package set for a specific official Arch ISO date.
# Run on an Internet-connected Arch Linux installation/VM/WSL environment.
#
# Usage:
#   ./offline/build_bundle.sh /path/to/archlinux-2026.08.01-x86_64.iso
#
# The script uses the Arch Linux Archive snapshot matching the ISO filename date,
# installs the minimal runtime into a temporary root with pacstrap, and keeps every
# downloaded package in offline/packages/. The diagnostic PC later installs only
# from those files and never contacts a mirror.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PKG_DIR="$REPO_ROOT/offline/packages"
ROOT_DIR="$REPO_ROOT/offline/.bundle-root"
LIST_FILE="$REPO_ROOT/offline/package-list.txt"
MANIFEST="$REPO_ROOT/offline/manifest.env"
ISO_PATH="${1:-}"

log() { printf '[bundle] %s\n' "$*"; }
die() { printf '[bundle] ERROR: %s\n' "$*" >&2; exit 2; }

[[ -n "$ISO_PATH" ]] || die "Usage: $0 /path/to/archlinux-YYYY.MM.DD-x86_64.iso"
[[ -f "$ISO_PATH" ]] || die "ISO not found: $ISO_PATH"
[[ -f "$LIST_FILE" ]] || die "Package list missing: $LIST_FILE"

ISO_NAME="$(basename "$ISO_PATH")"
if [[ "$ISO_NAME" =~ archlinux-([0-9]{4})\.([0-9]{2})\.([0-9]{2})-x86_64\.iso$ ]]; then
  YEAR="${BASH_REMATCH[1]}"; MONTH="${BASH_REMATCH[2]}"; DAY="${BASH_REMATCH[3]}"
else
  die "Expected an official ISO filename like archlinux-2026.08.01-x86_64.iso"
fi
ARCHISO_DATE="$YEAR.$MONTH.$DAY"
ARCHIVE_DATE="$YEAR/$MONTH/$DAY"

if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
  command -v sudo >/dev/null 2>&1 || die "sudo is required"
  exec sudo -E "$0" "$@"
fi

command -v pacman >/dev/null 2>&1 || die "Run this on Arch Linux."
pacman -Syu --needed --noconfirm arch-install-scripts archlinux-keyring
command -v pacstrap >/dev/null 2>&1 || die "pacstrap not available"

mapfile -t TARGETS < <(grep -Ev '^\s*(#|$)' "$LIST_FILE")
[[ ${#TARGETS[@]} -gt 0 ]] || die "Package list is empty"

rm -rf "$ROOT_DIR"
mkdir -p "$ROOT_DIR" "$PKG_DIR"
find "$PKG_DIR" -maxdepth 1 -type f ! -name .gitkeep -delete

PACCONF="$(mktemp)"
trap 'rm -f "$PACCONF"' EXIT
cat > "$PACCONF" <<CONF
[options]
Architecture = auto
CheckSpace
ParallelDownloads = 5
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
CacheDir = $PKG_DIR

[core]
Server = https://archive.archlinux.org/repos/$ARCHIVE_DATE/\$repo/os/\$arch

[extra]
Server = https://archive.archlinux.org/repos/$ARCHIVE_DATE/\$repo/os/\$arch
CONF

log "Building bundle against Arch archive snapshot $ARCHISO_DATE..."
log "This intentionally downloads a complete dependency closure; size is secondary to offline reliability."

# base + linux mirror the live environment fundamentals; targets add GPU runtime.
# -M keeps the host mirrorlist out of the temporary root; the custom archive config is used instead.
pacstrap -C "$PACCONF" -M "$ROOT_DIR" base linux "${TARGETS[@]}"

EXPECTED_KERNEL="$(find "$ROOT_DIR/usr/lib/modules" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' 2>/dev/null | grep -E '^[0-9].*-arch' | sort -V | tail -n1 || true)"
[[ -n "$EXPECTED_KERNEL" ]] || die "Could not determine expected Arch kernel from bundle root"

BUNDLE_CREATED="$(date --iso-8601=seconds)"
cat > "$MANIFEST" <<MANIFEST
# Generated by offline/build_bundle.sh
ARCHISO_DATE='$ARCHISO_DATE'
EXPECTED_KERNEL='$EXPECTED_KERNEL'
BUNDLE_CREATED='$BUNDLE_CREATED'
MANIFEST

(
  cd "$REPO_ROOT/offline"
  find packages -maxdepth 1 -type f -name '*.pkg.tar.zst' -print0 | sort -z | xargs -0 sha256sum > SHA256SUMS
)

log "Bundle complete."
log "Expected live kernel: $EXPECTED_KERNEL"
log "Packages: $(find "$PKG_DIR" -maxdepth 1 -type f -name '*.pkg.tar.zst' | wc -l)"
log "Size: $(du -sh "$PKG_DIR" | awk '{print $1}')"
log "Manifest: $MANIFEST"
rm -rf "$ROOT_DIR"
log "Temporary bundle root removed."
