#!/usr/bin/env python3
"""Resolve the official Arch ISO release and maintain offline/release.json.

offline/release.json is the single coupling between ISO, kernel and offline
bundle. It is generated by .github/workflows/bundle.yml and committed to the
repository; prepare-usb.ps1 reads nothing else. Staying on an older ISO
therefore means checking out an older commit instead of remembering which ISO
went with which bundle.

Subcommands (all usable by hand, not just from CI):

  iso [VERSION]   print KEY=value lines describing an official Arch ISO release
                  (default: the current one). Feed the output to $GITHUB_ENV,
                  $GITHUB_OUTPUT or a file for 'write --iso-meta'.
  write           assemble release.json from that metadata plus a built bundle
  check           re-validate an existing release.json, optionally against the
                  bundle file it describes

Only the standard library is used: this runs on the GitHub runner, not inside
the archlinux build container, so python3 is always available and jq is not
worth requiring.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

RELENG_JSON = "https://archlinux.org/releng/releases/json/"

# geo.mirror.pkgbuild.com is fast but only carries the current ISO;
# archive.archlinux.org carries every ISO forever. A release.json is used long
# after it was written, so both go into iso_urls, durable one last.
MIRROR_BASE = "https://geo.mirror.pkgbuild.com/iso"
ARCHIVE_BASE = "https://archive.archlinux.org/iso"

USER_AGENT = "gpu-triage-release-meta/1"
SCHEMA = 1

ISO_DATE_RE = re.compile(r"^\d{4}\.\d{2}\.\d{2}$")
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
MANIFEST_RE = re.compile(r"^([A-Z_][A-Z0-9_]*)='(.*)'$")

REQUIRED_FIELDS = (
    "schema",
    "iso_date",
    "iso_name",
    "iso_sha256",
    "iso_size",
    "iso_urls",
    "expected_kernel",
    "release_tag",
    "bundle_name",
    "bundle_url",
    "bundle_sha256",
    "bundle_size",
    "bundle_packages",
)


def die(message: str) -> "NoReturn":  # noqa: F821 - typing only
    print(f"[release-meta] ERROR: {message}", file=sys.stderr)
    raise SystemExit(2)


def log(message: str) -> None:
    print(f"[release-meta] {message}", file=sys.stderr)


def http_get(url: str, attempts: int = 3, timeout: int = 30) -> bytes:
    """GET with a couple of retries; mirrors and archive.archlinux.org flake."""
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    last: Exception | None = None
    for attempt in range(1, attempts + 1):
        try:
            with urllib.request.urlopen(request, timeout=timeout) as response:
                return response.read()
        except (urllib.error.URLError, TimeoutError, OSError) as error:
            last = error
            if attempt < attempts:
                time.sleep(2 * attempt)
    die(f"Could not fetch {url}: {last}")


def iso_name_for(iso_date: str) -> str:
    return f"archlinux-{iso_date}-x86_64.iso"


def iso_urls_for(iso_date: str) -> list[str]:
    name = iso_name_for(iso_date)
    return [f"{MIRROR_BASE}/{iso_date}/{name}", f"{ARCHIVE_BASE}/{iso_date}/{name}"]


def release_tag_for(iso_date: str) -> str:
    return f"bundle-{iso_date}"


def sha256sums_hash(iso_date: str, iso_name: str) -> str:
    """Read the ISO hash from the official sha256sums.txt next to the ISO.

    Second, independent source for the same value: the release list is a
    Django view, sha256sums.txt is generated with the images. Agreement of the
    two is what the download in CI is then verified against.
    """
    last_error = "no mirror tried"
    for base in (MIRROR_BASE, ARCHIVE_BASE):
        url = f"{base}/{iso_date}/sha256sums.txt"
        try:
            body = http_get(url, attempts=1).decode("utf-8", "replace")
        except SystemExit:
            last_error = f"unreachable: {url}"
            continue
        for line in body.splitlines():
            parts = line.split()
            if len(parts) == 2 and parts[1].lstrip("*") == iso_name:
                return parts[0].lower()
        last_error = f"{url} lists no entry for {iso_name}"
    die(f"Could not confirm the ISO hash against sha256sums.txt ({last_error}).")


def cmd_iso(args: argparse.Namespace) -> int:
    data = json.loads(http_get(RELENG_JSON))
    releases = data.get("releases") or []
    if not releases:
        die("The release list from archlinux.org contains no releases.")

    wanted = args.version
    if wanted in ("", "latest"):
        wanted = data.get("latest_version") or ""
        if not wanted:
            die("The release list names no latest_version.")

    entry = next((r for r in releases if r.get("version") == wanted), None)
    if entry is None:
        known = ", ".join(str(r.get("version")) for r in releases[:5])
        die(f"No Arch release {wanted!r} in the official list (newest: {known}).")

    iso_date = str(entry.get("version", ""))
    if not ISO_DATE_RE.match(iso_date):
        die(f"Release version {iso_date!r} is not a YYYY.MM.DD ISO date.")
    if not entry.get("available", False):
        die(f"Release {iso_date} is flagged as no longer available upstream.")

    iso_sha256 = str(entry.get("sha256_sum") or "").lower()
    if not SHA256_RE.match(iso_sha256):
        die(f"Release {iso_date} carries no usable sha256_sum.")

    iso_size = int(((entry.get("torrent") or {}).get("file_length")) or 0)
    if iso_size <= 0:
        die(f"Release {iso_date} carries no ISO file size.")

    iso_name = iso_name_for(iso_date)
    published = sha256sums_hash(iso_date, iso_name)
    if published != iso_sha256:
        die(
            "The two official sources disagree about the ISO hash.\n"
            f"  releng/releases/json: {iso_sha256}\n"
            f"  sha256sums.txt:       {published}\n"
            "Refusing to build against an ISO that cannot be pinned."
        )
    log(f"{iso_name}: hash confirmed by releng JSON and sha256sums.txt.")

    urls = iso_urls_for(iso_date)
    lines = [
        f"ISO_DATE={iso_date}",
        f"ISO_NAME={iso_name}",
        f"ISO_SHA256={iso_sha256}",
        f"ISO_SIZE={iso_size}",
        f"ISO_URL={urls[0]}",
        f"ISO_URL_ARCHIVE={urls[1]}",
        f"RELEASE_TAG={release_tag_for(iso_date)}",
    ]
    print("\n".join(lines))
    return 0


def read_key_values(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()
    return values


def read_manifest(path: Path) -> dict[str, str]:
    """Parse offline/manifest.env, which build_bundle.sh writes as KEY='value'."""
    if not path.is_file():
        die(f"Bundle manifest missing: {path} — build the bundle first.")
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = MANIFEST_RE.match(line)
        if match:
            values[match.group(1)] = match.group(2)
    return values


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def validate(release: dict) -> list[str]:
    """Everything prepare-usb.ps1 is entitled to assume about release.json."""
    problems: list[str] = []
    for field in REQUIRED_FIELDS:
        if field not in release:
            problems.append(f"missing field: {field}")
    if problems:
        return problems

    if release["schema"] != SCHEMA:
        problems.append(f"schema {release['schema']!r}, expected {SCHEMA}")

    iso_date = release["iso_date"]
    if not isinstance(iso_date, str) or not ISO_DATE_RE.match(iso_date):
        problems.append(f"iso_date {iso_date!r} is not YYYY.MM.DD")
    else:
        if release["iso_name"] != iso_name_for(iso_date):
            problems.append(
                f"iso_name {release['iso_name']!r} does not match iso_date {iso_date}"
            )
        if release["release_tag"] != release_tag_for(iso_date):
            problems.append(
                f"release_tag {release['release_tag']!r} does not match iso_date {iso_date}"
            )

    for field in ("iso_sha256", "bundle_sha256"):
        value = release[field]
        if not isinstance(value, str) or not SHA256_RE.match(value):
            problems.append(f"{field} is not a lowercase sha256 hex digest")

    for field in ("iso_size", "bundle_size", "bundle_packages"):
        value = release[field]
        if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
            problems.append(f"{field} is not a positive integer")

    urls = release["iso_urls"]
    if not isinstance(urls, list) or not urls:
        problems.append("iso_urls is empty")
    elif not all(isinstance(u, str) and u.startswith("https://") for u in urls):
        problems.append("iso_urls contains a non-https entry")
    elif not any(u.startswith(ARCHIVE_BASE) for u in urls):
        # Mirrors drop the ISO on the next release; without the archive a
        # pinned release.json stops working a month after it was written.
        problems.append("iso_urls has no archive.archlinux.org fallback")

    if not isinstance(release["expected_kernel"], str) or not release["expected_kernel"]:
        problems.append("expected_kernel is empty")

    bundle_url = release["bundle_url"]
    if not isinstance(bundle_url, str) or not bundle_url.startswith("https://"):
        problems.append("bundle_url is not an https URL")
    elif not bundle_url.endswith("/" + str(release["bundle_name"])):
        problems.append("bundle_url does not end in bundle_name")

    return problems


def cmd_write(args: argparse.Namespace) -> int:
    iso = read_key_values(Path(args.iso_meta))
    for key in ("ISO_DATE", "ISO_NAME", "ISO_SHA256", "ISO_SIZE"):
        if not iso.get(key):
            die(f"{args.iso_meta} has no {key} — generate it with 'release_meta.py iso'.")

    iso_date = iso["ISO_DATE"]
    manifest = read_manifest(Path(args.manifest))
    built_for = manifest.get("ARCHISO_DATE", "")
    if built_for != iso_date:
        die(
            "The built bundle does not belong to this ISO.\n"
            f"  manifest.env ARCHISO_DATE: {built_for or 'unset'}\n"
            f"  ISO metadata ISO_DATE:     {iso_date}\n"
            "release.json may only ever describe a matching pair."
        )
    expected_kernel = manifest.get("EXPECTED_KERNEL", "")
    if not expected_kernel:
        die("manifest.env carries no EXPECTED_KERNEL.")
    bundle_packages = int(manifest.get("BUNDLE_PACKAGES") or 0)
    if bundle_packages <= 0:
        die("manifest.env carries no usable BUNDLE_PACKAGES.")

    bundle = Path(args.bundle)
    if not bundle.is_file():
        die(f"Bundle artifact not found: {bundle}")

    release = {
        "schema": SCHEMA,
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "iso_date": iso_date,
        "iso_name": iso["ISO_NAME"],
        "iso_sha256": iso["ISO_SHA256"].lower(),
        "iso_size": int(iso["ISO_SIZE"]),
        "iso_urls": iso_urls_for(iso_date),
        "expected_kernel": expected_kernel,
        "release_tag": release_tag_for(iso_date),
        "bundle_name": bundle.name,
        "bundle_url": args.bundle_url,
        "bundle_sha256": sha256_file(bundle),
        "bundle_size": bundle.stat().st_size,
        "bundle_packages": bundle_packages,
    }

    problems = validate(release)
    if problems:
        die("Refusing to write an invalid release.json:\n  " + "\n  ".join(problems))

    out = Path(args.out)
    out.write_text(json.dumps(release, indent=2) + "\n", encoding="utf-8")
    log(f"Wrote {out} for ISO {iso_date}, kernel {expected_kernel}.")
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    path = Path(args.release)
    if not path.is_file():
        die(f"No release.json at {path}")
    try:
        release = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        die(f"{path} is not valid JSON: {error}")
    if not isinstance(release, dict):
        die(f"{path} does not contain a JSON object.")

    problems = validate(release)

    # The one claim that cannot be checked from the file alone: that the hash
    # and size really describe the artifact that was uploaded.
    if args.bundle:
        bundle = Path(args.bundle)
        if not bundle.is_file():
            problems.append(f"bundle not found: {bundle}")
        else:
            if bundle.name != release.get("bundle_name"):
                problems.append(
                    f"bundle_name {release.get('bundle_name')!r} != {bundle.name!r}"
                )
            actual_size = bundle.stat().st_size
            if actual_size != release.get("bundle_size"):
                problems.append(
                    f"bundle_size {release.get('bundle_size')!r} != {actual_size}"
                )
            actual_sha = sha256_file(bundle)
            if actual_sha != release.get("bundle_sha256"):
                problems.append(
                    f"bundle_sha256 {release.get('bundle_sha256')!r} != {actual_sha}"
                )
            else:
                log(f"bundle_sha256 matches {bundle.name}.")

    if problems:
        die(f"{path} is not usable:\n  " + "\n  ".join(problems))
    log(f"{path} is valid ({release['iso_name']} / {release['bundle_name']}).")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        prog="release_meta.py",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_iso = sub.add_parser("iso", help="print metadata for an official Arch ISO release")
    p_iso.add_argument("version", nargs="?", default="latest", help="YYYY.MM.DD or 'latest'")
    p_iso.set_defaults(func=cmd_iso)

    p_write = sub.add_parser("write", help="write offline/release.json")
    p_write.add_argument("--iso-meta", required=True, help="file produced by the 'iso' subcommand")
    p_write.add_argument("--bundle", required=True, help="path to gpu-triage-bundle-<date>.zip")
    p_write.add_argument("--bundle-url", required=True, help="public download URL of that file")
    p_write.add_argument("--manifest", default="offline/manifest.env")
    p_write.add_argument("--out", default="offline/release.json")
    p_write.set_defaults(func=cmd_write)

    p_check = sub.add_parser("check", help="validate an existing release.json")
    p_check.add_argument("--release", default="offline/release.json")
    p_check.add_argument("--bundle", help="also verify size and sha256 against this file")
    p_check.set_defaults(func=cmd_check)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
